---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-django
  template:
    metadata:
      labels:
        app: my-app-django
    spec:
      containers:
      - name: my-app-django
        image: richardmatheus929/todolist:latest
        ports:
        - containerPort: 8000
